library font_awesome_flutter;

import 'package:flutter/widgets.dart';
import 'package:font_awesome_flutter/icon_data.dart';

// THIS FILE IS AUTOMATICALLY GENERATED!
class FontAwesome {
  static IconData intBrands(int iconId) {
    return IconDataBrands(iconId);
  }

  static IconData intLight(int iconId) {
    return IconDataLight(iconId);
  }

  static IconData intRegular(int iconId) {
    return IconDataRegular(iconId);
  }

  static IconData intSolid(int iconId) {
    return IconDataSolid(iconId);
  }
}

class FontAwesomeId {
  static const int fa_500px = 0xf26e;

  static const int fa_abacus = 0xf640;

  static const int fa_accessible_icon = 0xf368;

  static const int fa_accusoft = 0xf369;

  static const int fa_acorn = 0xf6ae;

  static const int fa_acquisitions_incorporated = 0xf6af;

  static const int fa_ad = 0xf641;

  static const int fa_address_book = 0xf2b9;

  static const int fa_address_card = 0xf2bb;

  static const int fa_adjust = 0xf042;

  static const int fa_adn = 0xf170;

  static const int fa_adobe = 0xf778;

  static const int fa_adversal = 0xf36a;

  static const int fa_affiliatetheme = 0xf36b;

  static const int fa_air_freshener = 0xf5d0;

  static const int fa_airbnb = 0xf834;

  static const int fa_alarm_clock = 0xf34e;

  static const int fa_algolia = 0xf36c;

  static const int fa_alicorn = 0xf6b0;

  static const int fa_align_center = 0xf037;

  static const int fa_align_justify = 0xf039;

  static const int fa_align_left = 0xf036;

  static const int fa_align_right = 0xf038;

  static const int fa_alipay = 0xf642;

  static const int fa_allergies = 0xf461;

  static const int fa_amazon = 0xf270;

  static const int fa_amazon_pay = 0xf42c;

  static const int fa_ambulance = 0xf0f9;

  static const int fa_american_sign_language_interpreting = 0xf2a3;

  static const int fa_amilia = 0xf36d;

  static const int fa_analytics = 0xf643;

  static const int fa_anchor = 0xf13d;

  static const int fa_android = 0xf17b;

  static const int fa_angel = 0xf779;

  static const int fa_angellist = 0xf209;

  static const int fa_angle_double_down = 0xf103;

  static const int fa_angle_double_left = 0xf100;

  static const int fa_angle_double_right = 0xf101;

  static const int fa_angle_double_up = 0xf102;

  static const int fa_angle_down = 0xf107;

  static const int fa_angle_left = 0xf104;

  static const int fa_angle_right = 0xf105;

  static const int fa_angle_up = 0xf106;

  static const int fa_angry = 0xf556;

  static const int fa_angrycreative = 0xf36e;

  static const int fa_angular = 0xf420;

  static const int fa_ankh = 0xf644;

  static const int fa_app_store = 0xf36f;

  static const int fa_app_store_ios = 0xf370;

  static const int fa_apper = 0xf371;

  static const int fa_apple = 0xf179;

  static const int fa_apple_alt = 0xf5d1;

  static const int fa_apple_crate = 0xf6b1;

  static const int fa_apple_pay = 0xf415;

  static const int fa_archive = 0xf187;

  static const int fa_archway = 0xf557;

  static const int fa_arrow_alt_circle_down = 0xf358;

  static const int fa_arrow_alt_circle_left = 0xf359;

  static const int fa_arrow_alt_circle_right = 0xf35a;

  static const int fa_arrow_alt_circle_up = 0xf35b;

  static const int fa_arrow_alt_down = 0xf354;

  static const int fa_arrow_alt_from_bottom = 0xf346;

  static const int fa_arrow_alt_from_left = 0xf347;

  static const int fa_arrow_alt_from_right = 0xf348;

  static const int fa_arrow_alt_from_top = 0xf349;

  static const int fa_arrow_alt_left = 0xf355;

  static const int fa_arrow_alt_right = 0xf356;

  static const int fa_arrow_alt_square_down = 0xf350;

  static const int fa_arrow_alt_square_left = 0xf351;

  static const int fa_arrow_alt_square_right = 0xf352;

  static const int fa_arrow_alt_square_up = 0xf353;

  static const int fa_arrow_alt_to_bottom = 0xf34a;

  static const int fa_arrow_alt_to_left = 0xf34b;

  static const int fa_arrow_alt_to_right = 0xf34c;

  static const int fa_arrow_alt_to_top = 0xf34d;

  static const int fa_arrow_alt_up = 0xf357;

  static const int fa_arrow_circle_down = 0xf0ab;

  static const int fa_arrow_circle_left = 0xf0a8;

  static const int fa_arrow_circle_right = 0xf0a9;

  static const int fa_arrow_circle_up = 0xf0aa;

  static const int fa_arrow_down = 0xf063;

  static const int fa_arrow_from_bottom = 0xf342;

  static const int fa_arrow_from_left = 0xf343;

  static const int fa_arrow_from_right = 0xf344;

  static const int fa_arrow_from_top = 0xf345;

  static const int fa_arrow_left = 0xf060;

  static const int fa_arrow_right = 0xf061;

  static const int fa_arrow_square_down = 0xf339;

  static const int fa_arrow_square_left = 0xf33a;

  static const int fa_arrow_square_right = 0xf33b;

  static const int fa_arrow_square_up = 0xf33c;

  static const int fa_arrow_to_bottom = 0xf33d;

  static const int fa_arrow_to_left = 0xf33e;

  static const int fa_arrow_to_right = 0xf340;

  static const int fa_arrow_to_top = 0xf341;

  static const int fa_arrow_up = 0xf062;

  static const int fa_arrows = 0xf047;

  static const int fa_arrows_alt = 0xf0b2;

  static const int fa_arrows_alt_h = 0xf337;

  static const int fa_arrows_alt_v = 0xf338;

  static const int fa_arrows_h = 0xf07e;

  static const int fa_arrows_v = 0xf07d;

  static const int fa_artstation = 0xf77a;

  static const int fa_assistive_listening_systems = 0xf2a2;

  static const int fa_asterisk = 0xf069;

  static const int fa_asymmetrik = 0xf372;

  static const int fa_at = 0xf1fa;

  static const int fa_atlas = 0xf558;

  static const int fa_atlassian = 0xf77b;

  static const int fa_atom = 0xf5d2;

  static const int fa_atom_alt = 0xf5d3;

  static const int fa_audible = 0xf373;

  static const int fa_audio_description = 0xf29e;

  static const int fa_autoprefixer = 0xf41c;

  static const int fa_avianex = 0xf374;

  static const int fa_aviato = 0xf421;

  static const int fa_award = 0xf559;

  static const int fa_aws = 0xf375;

  static const int fa_axe = 0xf6b2;

  static const int fa_axe_battle = 0xf6b3;

  static const int fa_baby = 0xf77c;

  static const int fa_baby_carriage = 0xf77d;

  static const int fa_backpack = 0xf5d4;

  static const int fa_backspace = 0xf55a;

  static const int fa_backward = 0xf04a;

  static const int fa_bacon = 0xf7e5;

  static const int fa_badge = 0xf335;

  static const int fa_badge_check = 0xf336;

  static const int fa_badge_dollar = 0xf645;

  static const int fa_badge_percent = 0xf646;

  static const int fa_badger_honey = 0xf6b4;

  static const int fa_balance_scale = 0xf24e;

  static const int fa_balance_scale_left = 0xf515;

  static const int fa_balance_scale_right = 0xf516;

  static const int fa_ball_pile = 0xf77e;

  static const int fa_ballot = 0xf732;

  static const int fa_ballot_check = 0xf733;

  static const int fa_ban = 0xf05e;

  static const int fa_band_aid = 0xf462;

  static const int fa_bandcamp = 0xf2d5;

  static const int fa_barcode = 0xf02a;

  static const int fa_barcode_alt = 0xf463;

  static const int fa_barcode_read = 0xf464;

  static const int fa_barcode_scan = 0xf465;

  static const int fa_bars = 0xf0c9;

  static const int fa_baseball = 0xf432;

  static const int fa_baseball_ball = 0xf433;

  static const int fa_basketball_ball = 0xf434;

  static const int fa_basketball_hoop = 0xf435;

  static const int fa_bat = 0xf6b5;

  static const int fa_bath = 0xf2cd;

  static const int fa_battery_bolt = 0xf376;

  static const int fa_battery_empty = 0xf244;

  static const int fa_battery_full = 0xf240;

  static const int fa_battery_half = 0xf242;

  static const int fa_battery_quarter = 0xf243;

  static const int fa_battery_slash = 0xf377;

  static const int fa_battery_three_quarters = 0xf241;

  static const int fa_battle_net = 0xf835;

  static const int fa_bed = 0xf236;

  static const int fa_beer = 0xf0fc;

  static const int fa_behance = 0xf1b4;

  static const int fa_behance_square = 0xf1b5;

  static const int fa_bell = 0xf0f3;

  static const int fa_bell_school = 0xf5d5;

  static const int fa_bell_school_slash = 0xf5d6;

  static const int fa_bell_slash = 0xf1f6;

  static const int fa_bells = 0xf77f;

  static const int fa_bezier_curve = 0xf55b;

  static const int fa_bible = 0xf647;

  static const int fa_bicycle = 0xf206;

  static const int fa_bimobject = 0xf378;

  static const int fa_binoculars = 0xf1e5;

  static const int fa_biohazard = 0xf780;

  static const int fa_birthday_cake = 0xf1fd;

  static const int fa_bitbucket = 0xf171;

  static const int fa_bitcoin = 0xf379;

  static const int fa_bity = 0xf37a;

  static const int fa_black_tie = 0xf27e;

  static const int fa_blackberry = 0xf37b;

  static const int fa_blanket = 0xf498;

  static const int fa_blender = 0xf517;

  static const int fa_blender_phone = 0xf6b6;

  static const int fa_blind = 0xf29d;

  static const int fa_blog = 0xf781;

  static const int fa_blogger = 0xf37c;

  static const int fa_blogger_b = 0xf37d;

  static const int fa_bluetooth = 0xf293;

  static const int fa_bluetooth_b = 0xf294;

  static const int fa_bold = 0xf032;

  static const int fa_bolt = 0xf0e7;

  static const int fa_bomb = 0xf1e2;

  static const int fa_bone = 0xf5d7;

  static const int fa_bone_break = 0xf5d8;

  static const int fa_bong = 0xf55c;

  static const int fa_book = 0xf02d;

  static const int fa_book_alt = 0xf5d9;

  static const int fa_book_dead = 0xf6b7;

  static const int fa_book_heart = 0xf499;

  static const int fa_book_medical = 0xf7e6;

  static const int fa_book_open = 0xf518;

  static const int fa_book_reader = 0xf5da;

  static const int fa_book_spells = 0xf6b8;

  static const int fa_book_user = 0xf7e7;

  static const int fa_bookmark = 0xf02e;

  static const int fa_books = 0xf5db;

  static const int fa_books_medical = 0xf7e8;

  static const int fa_boot = 0xf782;

  static const int fa_booth_curtain = 0xf734;

  static const int fa_bootstrap = 0xf836;

  static const int fa_bow_arrow = 0xf6b9;

  static const int fa_bowling_ball = 0xf436;

  static const int fa_bowling_pins = 0xf437;

  static const int fa_box = 0xf466;

  static const int fa_box_alt = 0xf49a;

  static const int fa_box_ballot = 0xf735;

  static const int fa_box_check = 0xf467;

  static const int fa_box_fragile = 0xf49b;

  static const int fa_box_full = 0xf49c;

  static const int fa_box_heart = 0xf49d;

  static const int fa_box_open = 0xf49e;

  static const int fa_box_up = 0xf49f;

  static const int fa_box_usd = 0xf4a0;

  static const int fa_boxes = 0xf468;

  static const int fa_boxes_alt = 0xf4a1;

  static const int fa_boxing_glove = 0xf438;

  static const int fa_brackets = 0xf7e9;

  static const int fa_brackets_curly = 0xf7ea;

  static const int fa_braille = 0xf2a1;

  static const int fa_brain = 0xf5dc;

  static const int fa_bread_loaf = 0xf7eb;

  static const int fa_bread_slice = 0xf7ec;

  static const int fa_briefcase = 0xf0b1;

  static const int fa_briefcase_medical = 0xf469;

  static const int fa_broadcast_tower = 0xf519;

  static const int fa_broom = 0xf51a;

  static const int fa_browser = 0xf37e;

  static const int fa_brush = 0xf55d;

  static const int fa_btc = 0xf15a;

  static const int fa_buffer = 0xf837;

  static const int fa_bug = 0xf188;

  static const int fa_building = 0xf1ad;

  static const int fa_bullhorn = 0xf0a1;

  static const int fa_bullseye = 0xf140;

  static const int fa_bullseye_arrow = 0xf648;

  static const int fa_bullseye_pointer = 0xf649;

  static const int fa_burn = 0xf46a;

  static const int fa_buromobelexperte = 0xf37f;

  static const int fa_burrito = 0xf7ed;

  static const int fa_bus = 0xf207;

  static const int fa_bus_alt = 0xf55e;

  static const int fa_bus_school = 0xf5dd;

  static const int fa_business_time = 0xf64a;

  static const int fa_buysellads = 0xf20d;

  static const int fa_cabinet_filing = 0xf64b;

  static const int fa_calculator = 0xf1ec;

  static const int fa_calculator_alt = 0xf64c;

  static const int fa_calendar = 0xf133;

  static const int fa_calendar_alt = 0xf073;

  static const int fa_calendar_check = 0xf274;

  static const int fa_calendar_day = 0xf783;

  static const int fa_calendar_edit = 0xf333;

  static const int fa_calendar_exclamation = 0xf334;

  static const int fa_calendar_minus = 0xf272;

  static const int fa_calendar_plus = 0xf271;

  static const int fa_calendar_star = 0xf736;

  static const int fa_calendar_times = 0xf273;

  static const int fa_calendar_week = 0xf784;

  static const int fa_camera = 0xf030;

  static const int fa_camera_alt = 0xf332;

  static const int fa_camera_retro = 0xf083;

  static const int fa_campfire = 0xf6ba;

  static const int fa_campground = 0xf6bb;

  static const int fa_canadian_maple_leaf = 0xf785;

  static const int fa_candle_holder = 0xf6bc;

  static const int fa_candy_cane = 0xf786;

  static const int fa_candy_corn = 0xf6bd;

  static const int fa_cannabis = 0xf55f;

  static const int fa_capsules = 0xf46b;

  static const int fa_car = 0xf1b9;

  static const int fa_car_alt = 0xf5de;

  static const int fa_car_battery = 0xf5df;

  static const int fa_car_bump = 0xf5e0;

  static const int fa_car_crash = 0xf5e1;

  static const int fa_car_garage = 0xf5e2;

  static const int fa_car_mechanic = 0xf5e3;

  static const int fa_car_side = 0xf5e4;

  static const int fa_car_tilt = 0xf5e5;

  static const int fa_car_wash = 0xf5e6;

  static const int fa_caret_circle_down = 0xf32d;

  static const int fa_caret_circle_left = 0xf32e;

  static const int fa_caret_circle_right = 0xf330;

  static const int fa_caret_circle_up = 0xf331;

  static const int fa_caret_down = 0xf0d7;

  static const int fa_caret_left = 0xf0d9;

  static const int fa_caret_right = 0xf0da;

  static const int fa_caret_square_down = 0xf150;

  static const int fa_caret_square_left = 0xf191;

  static const int fa_caret_square_right = 0xf152;

  static const int fa_caret_square_up = 0xf151;

  static const int fa_caret_up = 0xf0d8;

  static const int fa_carrot = 0xf787;

  static const int fa_cart_arrow_down = 0xf218;

  static const int fa_cart_plus = 0xf217;

  static const int fa_cash_register = 0xf788;

  static const int fa_cat = 0xf6be;

  static const int fa_cauldron = 0xf6bf;

  static const int fa_cc_amazon_pay = 0xf42d;

  static const int fa_cc_amex = 0xf1f3;

  static const int fa_cc_apple_pay = 0xf416;

  static const int fa_cc_diners_club = 0xf24c;

  static const int fa_cc_discover = 0xf1f2;

  static const int fa_cc_jcb = 0xf24b;

  static const int fa_cc_mastercard = 0xf1f1;

  static const int fa_cc_paypal = 0xf1f4;

  static const int fa_cc_stripe = 0xf1f5;

  static const int fa_cc_visa = 0xf1f0;

  static const int fa_centercode = 0xf380;

  static const int fa_centos = 0xf789;

  static const int fa_certificate = 0xf0a3;

  static const int fa_chair = 0xf6c0;

  static const int fa_chair_office = 0xf6c1;

  static const int fa_chalkboard = 0xf51b;

  static const int fa_chalkboard_teacher = 0xf51c;

  static const int fa_charging_station = 0xf5e7;

  static const int fa_chart_area = 0xf1fe;

  static const int fa_chart_bar = 0xf080;

  static const int fa_chart_line = 0xf201;

  static const int fa_chart_line_down = 0xf64d;

  static const int fa_chart_network = 0xf78a;

  static const int fa_chart_pie = 0xf200;

  static const int fa_chart_pie_alt = 0xf64e;

  static const int fa_chart_scatter = 0xf7ee;

  static const int fa_check = 0xf00c;

  static const int fa_check_circle = 0xf058;

  static const int fa_check_double = 0xf560;

  static const int fa_check_square = 0xf14a;

  static const int fa_cheese = 0xf7ef;

  static const int fa_cheese_swiss = 0xf7f0;

  static const int fa_cheeseburger = 0xf7f1;

  static const int fa_chess = 0xf439;

  static const int fa_chess_bishop = 0xf43a;

  static const int fa_chess_bishop_alt = 0xf43b;

  static const int fa_chess_board = 0xf43c;

  static const int fa_chess_clock = 0xf43d;

  static const int fa_chess_clock_alt = 0xf43e;

  static const int fa_chess_king = 0xf43f;

  static const int fa_chess_king_alt = 0xf440;

  static const int fa_chess_knight = 0xf441;

  static const int fa_chess_knight_alt = 0xf442;

  static const int fa_chess_pawn = 0xf443;

  static const int fa_chess_pawn_alt = 0xf444;

  static const int fa_chess_queen = 0xf445;

  static const int fa_chess_queen_alt = 0xf446;

  static const int fa_chess_rook = 0xf447;

  static const int fa_chess_rook_alt = 0xf448;

  static const int fa_chevron_circle_down = 0xf13a;

  static const int fa_chevron_circle_left = 0xf137;

  static const int fa_chevron_circle_right = 0xf138;

  static const int fa_chevron_circle_up = 0xf139;

  static const int fa_chevron_double_down = 0xf322;

  static const int fa_chevron_double_left = 0xf323;

  static const int fa_chevron_double_right = 0xf324;

  static const int fa_chevron_double_up = 0xf325;

  static const int fa_chevron_down = 0xf078;

  static const int fa_chevron_left = 0xf053;

  static const int fa_chevron_right = 0xf054;

  static const int fa_chevron_square_down = 0xf329;

  static const int fa_chevron_square_left = 0xf32a;

  static const int fa_chevron_square_right = 0xf32b;

  static const int fa_chevron_square_up = 0xf32c;

  static const int fa_chevron_up = 0xf077;

  static const int fa_child = 0xf1ae;

  static const int fa_chimney = 0xf78b;

  static const int fa_chrome = 0xf268;

  static const int fa_chromecast = 0xf838;

  static const int fa_church = 0xf51d;

  static const int fa_circle = 0xf111;

  static const int fa_circle_notch = 0xf1ce;

  static const int fa_city = 0xf64f;

  static const int fa_claw_marks = 0xf6c2;

  static const int fa_clinic_medical = 0xf7f2;

  static const int fa_clipboard = 0xf328;

  static const int fa_clipboard_check = 0xf46c;

  static const int fa_clipboard_list = 0xf46d;

  static const int fa_clipboard_list_check = 0xf737;

  static const int fa_clipboard_prescription = 0xf5e8;

  static const int fa_clipboard_user = 0xf7f3;

  static const int fa_clock = 0xf017;

  static const int fa_clone = 0xf24d;

  static const int fa_closed_captioning = 0xf20a;

  static const int fa_cloud = 0xf0c2;

  static const int fa_cloud_download = 0xf0ed;

  static const int fa_cloud_download_alt = 0xf381;

  static const int fa_cloud_drizzle = 0xf738;

  static const int fa_cloud_hail = 0xf739;

  static const int fa_cloud_hail_mixed = 0xf73a;

  static const int fa_cloud_meatball = 0xf73b;

  static const int fa_cloud_moon = 0xf6c3;

  static const int fa_cloud_moon_rain = 0xf73c;

  static const int fa_cloud_rain = 0xf73d;

  static const int fa_cloud_rainbow = 0xf73e;

  static const int fa_cloud_showers = 0xf73f;

  static const int fa_cloud_showers_heavy = 0xf740;

  static const int fa_cloud_sleet = 0xf741;

  static const int fa_cloud_snow = 0xf742;

  static const int fa_cloud_sun = 0xf6c4;

  static const int fa_cloud_sun_rain = 0xf743;

  static const int fa_cloud_upload = 0xf0ee;

  static const int fa_cloud_upload_alt = 0xf382;

  static const int fa_clouds = 0xf744;

  static const int fa_clouds_moon = 0xf745;

  static const int fa_clouds_sun = 0xf746;

  static const int fa_cloudscale = 0xf383;

  static const int fa_cloudsmith = 0xf384;

  static const int fa_cloudversify = 0xf385;

  static const int fa_club = 0xf327;

  static const int fa_cocktail = 0xf561;

  static const int fa_code = 0xf121;

  static const int fa_code_branch = 0xf126;

  static const int fa_code_commit = 0xf386;

  static const int fa_code_merge = 0xf387;

  static const int fa_codepen = 0xf1cb;

  static const int fa_codiepie = 0xf284;

  static const int fa_coffee = 0xf0f4;

  static const int fa_coffee_togo = 0xf6c5;

  static const int fa_coffin = 0xf6c6;

  static const int fa_cog = 0xf013;

  static const int fa_cogs = 0xf085;

  static const int fa_coins = 0xf51e;

  static const int fa_columns = 0xf0db;

  static const int fa_comment = 0xf075;

  static const int fa_comment_alt = 0xf27a;

  static const int fa_comment_alt_check = 0xf4a2;

  static const int fa_comment_alt_dollar = 0xf650;

  static const int fa_comment_alt_dots = 0xf4a3;

  static const int fa_comment_alt_edit = 0xf4a4;

  static const int fa_comment_alt_exclamation = 0xf4a5;

  static const int fa_comment_alt_lines = 0xf4a6;

  static const int fa_comment_alt_medical = 0xf7f4;

  static const int fa_comment_alt_minus = 0xf4a7;

  static const int fa_comment_alt_plus = 0xf4a8;

  static const int fa_comment_alt_slash = 0xf4a9;

  static const int fa_comment_alt_smile = 0xf4aa;

  static const int fa_comment_alt_times = 0xf4ab;

  static const int fa_comment_check = 0xf4ac;

  static const int fa_comment_dollar = 0xf651;

  static const int fa_comment_dots = 0xf4ad;

  static const int fa_comment_edit = 0xf4ae;

  static const int fa_comment_exclamation = 0xf4af;

  static const int fa_comment_lines = 0xf4b0;

  static const int fa_comment_medical = 0xf7f5;

  static const int fa_comment_minus = 0xf4b1;

  static const int fa_comment_plus = 0xf4b2;

  static const int fa_comment_slash = 0xf4b3;

  static const int fa_comment_smile = 0xf4b4;

  static const int fa_comment_times = 0xf4b5;

  static const int fa_comments = 0xf086;

  static const int fa_comments_alt = 0xf4b6;

  static const int fa_comments_alt_dollar = 0xf652;

  static const int fa_comments_dollar = 0xf653;

  static const int fa_compact_disc = 0xf51f;

  static const int fa_compass = 0xf14e;

  static const int fa_compass_slash = 0xf5e9;

  static const int fa_compress = 0xf066;

  static const int fa_compress_alt = 0xf422;

  static const int fa_compress_arrows_alt = 0xf78c;

  static const int fa_compress_wide = 0xf326;

  static const int fa_concierge_bell = 0xf562;

  static const int fa_confluence = 0xf78d;

  static const int fa_connectdevelop = 0xf20e;

  static const int fa_container_storage = 0xf4b7;

  static const int fa_contao = 0xf26d;

  static const int fa_conveyor_belt = 0xf46e;

  static const int fa_conveyor_belt_alt = 0xf46f;

  static const int fa_cookie = 0xf563;

  static const int fa_cookie_bite = 0xf564;

  static const int fa_copy = 0xf0c5;

  static const int fa_copyright = 0xf1f9;

  static const int fa_corn = 0xf6c7;

  static const int fa_couch = 0xf4b8;

  static const int fa_cow = 0xf6c8;

  static const int fa_cpanel = 0xf388;

  static const int fa_creative_commons = 0xf25e;

  static const int fa_creative_commons_by = 0xf4e7;

  static const int fa_creative_commons_nc = 0xf4e8;

  static const int fa_creative_commons_nc_eu = 0xf4e9;

  static const int fa_creative_commons_nc_jp = 0xf4ea;

  static const int fa_creative_commons_nd = 0xf4eb;

  static const int fa_creative_commons_pd = 0xf4ec;

  static const int fa_creative_commons_pd_alt = 0xf4ed;

  static const int fa_creative_commons_remix = 0xf4ee;

  static const int fa_creative_commons_sa = 0xf4ef;

  static const int fa_creative_commons_sampling = 0xf4f0;

  static const int fa_creative_commons_sampling_plus = 0xf4f1;

  static const int fa_creative_commons_share = 0xf4f2;

  static const int fa_creative_commons_zero = 0xf4f3;

  static const int fa_credit_card = 0xf09d;

  static const int fa_credit_card_blank = 0xf389;

  static const int fa_credit_card_front = 0xf38a;

  static const int fa_cricket = 0xf449;

  static const int fa_critical_role = 0xf6c9;

  static const int fa_croissant = 0xf7f6;

  static const int fa_crop = 0xf125;

  static const int fa_crop_alt = 0xf565;

  static const int fa_cross = 0xf654;

  static const int fa_crosshairs = 0xf05b;

  static const int fa_crow = 0xf520;

  static const int fa_crown = 0xf521;

  static const int fa_crutch = 0xf7f7;

  static const int fa_crutches = 0xf7f8;

  static const int fa_css3 = 0xf13c;

  static const int fa_css3_alt = 0xf38b;

  static const int fa_cube = 0xf1b2;

  static const int fa_cubes = 0xf1b3;

  static const int fa_curling = 0xf44a;

  static const int fa_cut = 0xf0c4;

  static const int fa_cuttlefish = 0xf38c;

  static const int fa_d_and_d = 0xf38d;

  static const int fa_d_and_d_beyond = 0xf6ca;

  static const int fa_dagger = 0xf6cb;

  static const int fa_dashcube = 0xf210;

  static const int fa_database = 0xf1c0;

  static const int fa_deaf = 0xf2a4;

  static const int fa_debug = 0xf7f9;

  static const int fa_deer = 0xf78e;

  static const int fa_deer_rudolph = 0xf78f;

  static const int fa_delicious = 0xf1a5;

  static const int fa_democrat = 0xf747;

  static const int fa_deploydog = 0xf38e;

  static const int fa_deskpro = 0xf38f;

  static const int fa_desktop = 0xf108;

  static const int fa_desktop_alt = 0xf390;

  static const int fa_dev = 0xf6cc;

  static const int fa_deviantart = 0xf1bd;

  static const int fa_dewpoint = 0xf748;

  static const int fa_dharmachakra = 0xf655;

  static const int fa_dhl = 0xf790;

  static const int fa_diagnoses = 0xf470;

  static const int fa_diamond = 0xf219;

  static const int fa_diaspora = 0xf791;

  static const int fa_dice = 0xf522;

  static const int fa_dice_d10 = 0xf6cd;

  static const int fa_dice_d12 = 0xf6ce;

  static const int fa_dice_d20 = 0xf6cf;

  static const int fa_dice_d4 = 0xf6d0;

  static const int fa_dice_d6 = 0xf6d1;

  static const int fa_dice_d8 = 0xf6d2;

  static const int fa_dice_five = 0xf523;

  static const int fa_dice_four = 0xf524;

  static const int fa_dice_one = 0xf525;

  static const int fa_dice_six = 0xf526;

  static const int fa_dice_three = 0xf527;

  static const int fa_dice_two = 0xf528;

  static const int fa_digg = 0xf1a6;

  static const int fa_digital_ocean = 0xf391;

  static const int fa_digital_tachograph = 0xf566;

  static const int fa_diploma = 0xf5ea;

  static const int fa_directions = 0xf5eb;

  static const int fa_discord = 0xf392;

  static const int fa_discourse = 0xf393;

  static const int fa_disease = 0xf7fa;

  static const int fa_divide = 0xf529;

  static const int fa_dizzy = 0xf567;

  static const int fa_dna = 0xf471;

  static const int fa_do_not_enter = 0xf5ec;

  static const int fa_dochub = 0xf394;

  static const int fa_docker = 0xf395;

  static const int fa_dog = 0xf6d3;

  static const int fa_dog_leashed = 0xf6d4;

  static const int fa_dollar_sign = 0xf155;

  static const int fa_dolly = 0xf472;

  static const int fa_dolly_empty = 0xf473;

  static const int fa_dolly_flatbed = 0xf474;

  static const int fa_dolly_flatbed_alt = 0xf475;

  static const int fa_dolly_flatbed_empty = 0xf476;

  static const int fa_donate = 0xf4b9;

  static const int fa_door_closed = 0xf52a;

  static const int fa_door_open = 0xf52b;

  static const int fa_dot_circle = 0xf192;

  static const int fa_dove = 0xf4ba;

  static const int fa_download = 0xf019;

  static const int fa_draft2digital = 0xf396;

  static const int fa_drafting_compass = 0xf568;

  static const int fa_dragon = 0xf6d5;

  static const int fa_draw_circle = 0xf5ed;

  static const int fa_draw_polygon = 0xf5ee;

  static const int fa_draw_square = 0xf5ef;

  static const int fa_dreidel = 0xf792;

  static const int fa_dribbble = 0xf17d;

  static const int fa_dribbble_square = 0xf397;

  static const int fa_dropbox = 0xf16b;

  static const int fa_drum = 0xf569;

  static const int fa_drum_steelpan = 0xf56a;

  static const int fa_drumstick = 0xf6d6;

  static const int fa_drumstick_bite = 0xf6d7;

  static const int fa_drupal = 0xf1a9;

  static const int fa_duck = 0xf6d8;

  static const int fa_dumbbell = 0xf44b;

  static const int fa_dumpster = 0xf793;

  static const int fa_dumpster_fire = 0xf794;

  static const int fa_dungeon = 0xf6d9;

  static const int fa_dyalog = 0xf399;

  static const int fa_ear = 0xf5f0;

  static const int fa_ear_muffs = 0xf795;

  static const int fa_earlybirds = 0xf39a;

  static const int fa_ebay = 0xf4f4;

  static const int fa_eclipse = 0xf749;

  static const int fa_eclipse_alt = 0xf74a;

  static const int fa_edge = 0xf282;

  static const int fa_edit = 0xf044;

  static const int fa_egg = 0xf7fb;

  static const int fa_egg_fried = 0xf7fc;

  static const int fa_eject = 0xf052;

  static const int fa_elementor = 0xf430;

  static const int fa_elephant = 0xf6da;

  static const int fa_ellipsis_h = 0xf141;

  static const int fa_ellipsis_h_alt = 0xf39b;

  static const int fa_ellipsis_v = 0xf142;

  static const int fa_ellipsis_v_alt = 0xf39c;

  static const int fa_ello = 0xf5f1;

  static const int fa_ember = 0xf423;

  static const int fa_empire = 0xf1d1;

  static const int fa_empty_set = 0xf656;

  static const int fa_engine_warning = 0xf5f2;

  static const int fa_envelope = 0xf0e0;

  static const int fa_envelope_open = 0xf2b6;

  static const int fa_envelope_open_dollar = 0xf657;

  static const int fa_envelope_open_text = 0xf658;

  static const int fa_envelope_square = 0xf199;

  static const int fa_envira = 0xf299;

  static const int fa_equals = 0xf52c;

  static const int fa_eraser = 0xf12d;

  static const int fa_erlang = 0xf39d;

  static const int fa_ethereum = 0xf42e;

  static const int fa_ethernet = 0xf796;

  static const int fa_etsy = 0xf2d7;

  static const int fa_euro_sign = 0xf153;

  static const int fa_evernote = 0xf839;

  static const int fa_exchange = 0xf0ec;

  static const int fa_exchange_alt = 0xf362;

  static const int fa_exclamation = 0xf12a;

  static const int fa_exclamation_circle = 0xf06a;

  static const int fa_exclamation_square = 0xf321;

  static const int fa_exclamation_triangle = 0xf071;

  static const int fa_expand = 0xf065;

  static const int fa_expand_alt = 0xf424;

  static const int fa_expand_arrows = 0xf31d;

  static const int fa_expand_arrows_alt = 0xf31e;

  static const int fa_expand_wide = 0xf320;

  static const int fa_expeditedssl = 0xf23e;

  static const int fa_external_link = 0xf08e;

  static const int fa_external_link_alt = 0xf35d;

  static const int fa_external_link_square = 0xf14c;

  static const int fa_external_link_square_alt = 0xf360;

  static const int fa_eye = 0xf06e;

  static const int fa_eye_dropper = 0xf1fb;

  static const int fa_eye_evil = 0xf6db;

  static const int fa_eye_slash = 0xf070;

  static const int fa_facebook = 0xf09a;

  static const int fa_facebook_f = 0xf39e;

  static const int fa_facebook_messenger = 0xf39f;

  static const int fa_facebook_square = 0xf082;

  static const int fa_fantasy_flight_games = 0xf6dc;

  static const int fa_fast_backward = 0xf049;

  static const int fa_fast_forward = 0xf050;

  static const int fa_fax = 0xf1ac;

  static const int fa_feather = 0xf52d;

  static const int fa_feather_alt = 0xf56b;

  static const int fa_fedex = 0xf797;

  static const int fa_fedora = 0xf798;

  static const int fa_female = 0xf182;

  static const int fa_field_hockey = 0xf44c;

  static const int fa_fighter_jet = 0xf0fb;

  static const int fa_figma = 0xf799;

  static const int fa_file = 0xf15b;

  static const int fa_file_alt = 0xf15c;

  static const int fa_file_archive = 0xf1c6;

  static const int fa_file_audio = 0xf1c7;

  static const int fa_file_certificate = 0xf5f3;

  static const int fa_file_chart_line = 0xf659;

  static const int fa_file_chart_pie = 0xf65a;

  static const int fa_file_check = 0xf316;

  static const int fa_file_code = 0xf1c9;

  static const int fa_file_contract = 0xf56c;

  static const int fa_file_csv = 0xf6dd;

  static const int fa_file_download = 0xf56d;

  static const int fa_file_edit = 0xf31c;

  static const int fa_file_excel = 0xf1c3;

  static const int fa_file_exclamation = 0xf31a;

  static const int fa_file_export = 0xf56e;

  static const int fa_file_image = 0xf1c5;

  static const int fa_file_import = 0xf56f;

  static const int fa_file_invoice = 0xf570;

  static const int fa_file_invoice_dollar = 0xf571;

  static const int fa_file_medical = 0xf477;

  static const int fa_file_medical_alt = 0xf478;

  static const int fa_file_minus = 0xf318;

  static const int fa_file_pdf = 0xf1c1;

  static const int fa_file_plus = 0xf319;

  static const int fa_file_powerpoint = 0xf1c4;

  static const int fa_file_prescription = 0xf572;

  static const int fa_file_signature = 0xf573;

  static const int fa_file_spreadsheet = 0xf65b;

  static const int fa_file_times = 0xf317;

  static const int fa_file_upload = 0xf574;

  static const int fa_file_user = 0xf65c;

  static const int fa_file_video = 0xf1c8;

  static const int fa_file_word = 0xf1c2;

  static const int fa_files_medical = 0xf7fd;

  static const int fa_fill = 0xf575;

  static const int fa_fill_drip = 0xf576;

  static const int fa_film = 0xf008;

  static const int fa_film_alt = 0xf3a0;

  static const int fa_filter = 0xf0b0;

  static const int fa_fingerprint = 0xf577;

  static const int fa_fire = 0xf06d;

  static const int fa_fire_alt = 0xf7e4;

  static const int fa_fire_extinguisher = 0xf134;

  static const int fa_fire_smoke = 0xf74b;

  static const int fa_firefox = 0xf269;

  static const int fa_fireplace = 0xf79a;

  static const int fa_first_aid = 0xf479;

  static const int fa_first_order = 0xf2b0;

  static const int fa_first_order_alt = 0xf50a;

  static const int fa_firstdraft = 0xf3a1;

  static const int fa_fish = 0xf578;

  static const int fa_fish_cooked = 0xf7fe;

  static const int fa_fist_raised = 0xf6de;

  static const int fa_flag = 0xf024;

  static const int fa_flag_alt = 0xf74c;

  static const int fa_flag_checkered = 0xf11e;

  static const int fa_flag_usa = 0xf74d;

  static const int fa_flame = 0xf6df;

  static const int fa_flask = 0xf0c3;

  static const int fa_flask_poison = 0xf6e0;

  static const int fa_flask_potion = 0xf6e1;

  static const int fa_flickr = 0xf16e;

  static const int fa_flipboard = 0xf44d;

  static const int fa_flower = 0xf7ff;

  static const int fa_flower_daffodil = 0xf800;

  static const int fa_flower_tulip = 0xf801;

  static const int fa_flushed = 0xf579;

  static const int fa_fly = 0xf417;

  static const int fa_fog = 0xf74e;

  static const int fa_folder = 0xf07b;

  static const int fa_folder_minus = 0xf65d;

  static const int fa_folder_open = 0xf07c;

  static const int fa_folder_plus = 0xf65e;

  static const int fa_folder_times = 0xf65f;

  static const int fa_folder_tree = 0xf802;

  static const int fa_folders = 0xf660;

  static const int fa_font = 0xf031;

  static const int fa_font_awesome = 0xf2b4;

  static const int fa_font_awesome_alt = 0xf35c;

  static const int fa_font_awesome_flag = 0xf425;

  static const int fa_font_awesome_logo_full = 0xf4e6;

  static const int fa_fonticons = 0xf280;

  static const int fa_fonticons_fi = 0xf3a2;

  static const int fa_football_ball = 0xf44e;

  static const int fa_football_helmet = 0xf44f;

  static const int fa_forklift = 0xf47a;

  static const int fa_fort_awesome = 0xf286;

  static const int fa_fort_awesome_alt = 0xf3a3;

  static const int fa_forumbee = 0xf211;

  static const int fa_forward = 0xf04e;

  static const int fa_foursquare = 0xf180;

  static const int fa_fragile = 0xf4bb;

  static const int fa_free_code_camp = 0xf2c5;

  static const int fa_freebsd = 0xf3a4;

  static const int fa_french_fries = 0xf803;

  static const int fa_frog = 0xf52e;

  static const int fa_frosty_head = 0xf79b;

  static const int fa_frown = 0xf119;

  static const int fa_frown_open = 0xf57a;

  static const int fa_fulcrum = 0xf50b;

  static const int fa_function = 0xf661;

  static const int fa_funnel_dollar = 0xf662;

  static const int fa_futbol = 0xf1e3;

  static const int fa_galactic_republic = 0xf50c;

  static const int fa_galactic_senate = 0xf50d;

  static const int fa_gamepad = 0xf11b;

  static const int fa_gas_pump = 0xf52f;

  static const int fa_gas_pump_slash = 0xf5f4;

  static const int fa_gavel = 0xf0e3;

  static const int fa_gem = 0xf3a5;

  static const int fa_genderless = 0xf22d;

  static const int fa_get_pocket = 0xf265;

  static const int fa_gg = 0xf260;

  static const int fa_gg_circle = 0xf261;

  static const int fa_ghost = 0xf6e2;

  static const int fa_gift = 0xf06b;

  static const int fa_gift_card = 0xf663;

  static const int fa_gifts = 0xf79c;

  static const int fa_gingerbread_man = 0xf79d;

  static const int fa_git = 0xf1d3;

  static const int fa_git_square = 0xf1d2;

  static const int fa_github = 0xf09b;

  static const int fa_github_alt = 0xf113;

  static const int fa_github_square = 0xf092;

  static const int fa_gitkraken = 0xf3a6;

  static const int fa_gitlab = 0xf296;

  static const int fa_gitter = 0xf426;

  static const int fa_glass = 0xf804;

  static const int fa_glass_champagne = 0xf79e;

  static const int fa_glass_cheers = 0xf79f;

  static const int fa_glass_martini = 0xf000;

  static const int fa_glass_martini_alt = 0xf57b;

  static const int fa_glass_whiskey = 0xf7a0;

  static const int fa_glass_whiskey_rocks = 0xf7a1;

  static const int fa_glasses = 0xf530;

  static const int fa_glasses_alt = 0xf5f5;

  static const int fa_glide = 0xf2a5;

  static const int fa_glide_g = 0xf2a6;

  static const int fa_globe = 0xf0ac;

  static const int fa_globe_africa = 0xf57c;

  static const int fa_globe_americas = 0xf57d;

  static const int fa_globe_asia = 0xf57e;

  static const int fa_globe_europe = 0xf7a2;

  static const int fa_globe_snow = 0xf7a3;

  static const int fa_globe_stand = 0xf5f6;

  static const int fa_gofore = 0xf3a7;

  static const int fa_golf_ball = 0xf450;

  static const int fa_golf_club = 0xf451;

  static const int fa_goodreads = 0xf3a8;

  static const int fa_goodreads_g = 0xf3a9;

  static const int fa_google = 0xf1a0;

  static const int fa_google_drive = 0xf3aa;

  static const int fa_google_play = 0xf3ab;

  static const int fa_google_plus = 0xf2b3;

  static const int fa_google_plus_g = 0xf0d5;

  static const int fa_google_plus_square = 0xf0d4;

  static const int fa_google_wallet = 0xf1ee;

  static const int fa_gopuram = 0xf664;

  static const int fa_graduation_cap = 0xf19d;

  static const int fa_gratipay = 0xf184;

  static const int fa_grav = 0xf2d6;

  static const int fa_greater_than = 0xf531;

  static const int fa_greater_than_equal = 0xf532;

  static const int fa_grimace = 0xf57f;

  static const int fa_grin = 0xf580;

  static const int fa_grin_alt = 0xf581;

  static const int fa_grin_beam = 0xf582;

  static const int fa_grin_beam_sweat = 0xf583;

  static const int fa_grin_hearts = 0xf584;

  static const int fa_grin_squint = 0xf585;

  static const int fa_grin_squint_tears = 0xf586;

  static const int fa_grin_stars = 0xf587;

  static const int fa_grin_tears = 0xf588;

  static const int fa_grin_tongue = 0xf589;

  static const int fa_grin_tongue_squint = 0xf58a;

  static const int fa_grin_tongue_wink = 0xf58b;

  static const int fa_grin_wink = 0xf58c;

  static const int fa_grip_horizontal = 0xf58d;

  static const int fa_grip_lines = 0xf7a4;

  static const int fa_grip_lines_vertical = 0xf7a5;

  static const int fa_grip_vertical = 0xf58e;

  static const int fa_gripfire = 0xf3ac;

  static const int fa_grunt = 0xf3ad;

  static const int fa_guitar = 0xf7a6;

  static const int fa_gulp = 0xf3ae;

  static const int fa_h_square = 0xf0fd;

  static const int fa_h1 = 0xf313;

  static const int fa_h2 = 0xf314;

  static const int fa_h3 = 0xf315;

  static const int fa_hacker_news = 0xf1d4;

  static const int fa_hacker_news_square = 0xf3af;

  static const int fa_hackerrank = 0xf5f7;

  static const int fa_hamburger = 0xf805;

  static const int fa_hammer = 0xf6e3;

  static const int fa_hammer_war = 0xf6e4;

  static const int fa_hamsa = 0xf665;

  static const int fa_hand_heart = 0xf4bc;

  static const int fa_hand_holding = 0xf4bd;

  static const int fa_hand_holding_box = 0xf47b;

  static const int fa_hand_holding_heart = 0xf4be;

  static const int fa_hand_holding_magic = 0xf6e5;

  static const int fa_hand_holding_seedling = 0xf4bf;

  static const int fa_hand_holding_usd = 0xf4c0;

  static const int fa_hand_holding_water = 0xf4c1;

  static const int fa_hand_lizard = 0xf258;

  static const int fa_hand_middle_finger = 0xf806;

  static const int fa_hand_paper = 0xf256;

  static const int fa_hand_peace = 0xf25b;

  static const int fa_hand_point_down = 0xf0a7;

  static const int fa_hand_point_left = 0xf0a5;

  static const int fa_hand_point_right = 0xf0a4;

  static const int fa_hand_point_up = 0xf0a6;

  static const int fa_hand_pointer = 0xf25a;

  static const int fa_hand_receiving = 0xf47c;

  static const int fa_hand_rock = 0xf255;

  static const int fa_hand_scissors = 0xf257;

  static const int fa_hand_spock = 0xf259;

  static const int fa_hands = 0xf4c2;

  static const int fa_hands_heart = 0xf4c3;

  static const int fa_hands_helping = 0xf4c4;

  static const int fa_hands_usd = 0xf4c5;

  static const int fa_handshake = 0xf2b5;

  static const int fa_handshake_alt = 0xf4c6;

  static const int fa_hanukiah = 0xf6e6;

  static const int fa_hard_hat = 0xf807;

  static const int fa_hashtag = 0xf292;

  static const int fa_hat_santa = 0xf7a7;

  static const int fa_hat_winter = 0xf7a8;

  static const int fa_hat_witch = 0xf6e7;

  static const int fa_hat_wizard = 0xf6e8;

  static const int fa_haykal = 0xf666;

  static const int fa_hdd = 0xf0a0;

  static const int fa_head_side = 0xf6e9;

  static const int fa_head_side_brain = 0xf808;

  static const int fa_head_side_medical = 0xf809;

  static const int fa_head_vr = 0xf6ea;

  static const int fa_heading = 0xf1dc;

  static const int fa_headphones = 0xf025;

  static const int fa_headphones_alt = 0xf58f;

  static const int fa_headset = 0xf590;

  static const int fa_heart = 0xf004;

  static const int fa_heart_broken = 0xf7a9;

  static const int fa_heart_circle = 0xf4c7;

  static const int fa_heart_rate = 0xf5f8;

  static const int fa_heart_square = 0xf4c8;

  static const int fa_heartbeat = 0xf21e;

  static const int fa_helicopter = 0xf533;

  static const int fa_helmet_battle = 0xf6eb;

  static const int fa_hexagon = 0xf312;

  static const int fa_highlighter = 0xf591;

  static const int fa_hiking = 0xf6ec;

  static const int fa_hippo = 0xf6ed;

  static const int fa_hips = 0xf452;

  static const int fa_hire_a_helper = 0xf3b0;

  static const int fa_history = 0xf1da;

  static const int fa_hockey_mask = 0xf6ee;

  static const int fa_hockey_puck = 0xf453;

  static const int fa_hockey_sticks = 0xf454;

  static const int fa_holly_berry = 0xf7aa;

  static const int fa_home = 0xf015;

  static const int fa_home_alt = 0xf80a;

  static const int fa_home_heart = 0xf4c9;

  static const int fa_home_lg = 0xf80b;

  static const int fa_home_lg_alt = 0xf80c;

  static const int fa_hood_cloak = 0xf6ef;

  static const int fa_hooli = 0xf427;

  static const int fa_hornbill = 0xf592;

  static const int fa_horse = 0xf6f0;

  static const int fa_horse_head = 0xf7ab;

  static const int fa_hospital = 0xf0f8;

  static const int fa_hospital_alt = 0xf47d;

  static const int fa_hospital_symbol = 0xf47e;

  static const int fa_hospital_user = 0xf80d;

  static const int fa_hospitals = 0xf80e;

  static const int fa_hot_tub = 0xf593;

  static const int fa_hotdog = 0xf80f;

  static const int fa_hotel = 0xf594;

  static const int fa_hotjar = 0xf3b1;

  static const int fa_hourglass = 0xf254;

  static const int fa_hourglass_end = 0xf253;

  static const int fa_hourglass_half = 0xf252;

  static const int fa_hourglass_start = 0xf251;

  static const int fa_house_damage = 0xf6f1;

  static const int fa_house_flood = 0xf74f;

  static const int fa_houzz = 0xf27c;

  static const int fa_hryvnia = 0xf6f2;

  static const int fa_html5 = 0xf13b;

  static const int fa_hubspot = 0xf3b2;

  static const int fa_humidity = 0xf750;

  static const int fa_hurricane = 0xf751;

  static const int fa_i_cursor = 0xf246;

  static const int fa_ice_cream = 0xf810;

  static const int fa_ice_skate = 0xf7ac;

  static const int fa_icicles = 0xf7ad;

  static const int fa_id_badge = 0xf2c1;

  static const int fa_id_card = 0xf2c2;

  static const int fa_id_card_alt = 0xf47f;

  static const int fa_igloo = 0xf7ae;

  static const int fa_image = 0xf03e;

  static const int fa_images = 0xf302;

  static const int fa_imdb = 0xf2d8;

  static const int fa_inbox = 0xf01c;

  static const int fa_inbox_in = 0xf310;

  static const int fa_inbox_out = 0xf311;

  static const int fa_indent = 0xf03c;

  static const int fa_industry = 0xf275;

  static const int fa_industry_alt = 0xf3b3;

  static const int fa_infinity = 0xf534;

  static const int fa_info = 0xf129;

  static const int fa_info_circle = 0xf05a;

  static const int fa_info_square = 0xf30f;

  static const int fa_inhaler = 0xf5f9;

  static const int fa_instagram = 0xf16d;

  static const int fa_integral = 0xf667;

  static const int fa_intercom = 0xf7af;

  static const int fa_internet_explorer = 0xf26b;

  static const int fa_intersection = 0xf668;

  static const int fa_inventory = 0xf480;

  static const int fa_invision = 0xf7b0;

  static const int fa_ioxhost = 0xf208;

  static const int fa_island_tropical = 0xf811;

  static const int fa_italic = 0xf033;

  static const int fa_itch_io = 0xf83a;

  static const int fa_itunes = 0xf3b4;

  static const int fa_itunes_note = 0xf3b5;

  static const int fa_jack_o_lantern = 0xf30e;

  static const int fa_java = 0xf4e4;

  static const int fa_jedi = 0xf669;

  static const int fa_jedi_order = 0xf50e;

  static const int fa_jenkins = 0xf3b6;

  static const int fa_jira = 0xf7b1;

  static const int fa_joget = 0xf3b7;

  static const int fa_joint = 0xf595;

  static const int fa_joomla = 0xf1aa;

  static const int fa_journal_whills = 0xf66a;

  static const int fa_js = 0xf3b8;

  static const int fa_js_square = 0xf3b9;

  static const int fa_jsfiddle = 0xf1cc;

  static const int fa_kaaba = 0xf66b;

  static const int fa_kaggle = 0xf5fa;

  static const int fa_key = 0xf084;

  static const int fa_key_skeleton = 0xf6f3;

  static const int fa_keybase = 0xf4f5;

  static const int fa_keyboard = 0xf11c;

  static const int fa_keycdn = 0xf3ba;

  static const int fa_keynote = 0xf66c;

  static const int fa_khanda = 0xf66d;

  static const int fa_kickstarter = 0xf3bb;

  static const int fa_kickstarter_k = 0xf3bc;

  static const int fa_kidneys = 0xf5fb;

  static const int fa_kiss = 0xf596;

  static const int fa_kiss_beam = 0xf597;

  static const int fa_kiss_wink_heart = 0xf598;

  static const int fa_kite = 0xf6f4;

  static const int fa_kiwi_bird = 0xf535;

  static const int fa_knife_kitchen = 0xf6f5;

  static const int fa_korvue = 0xf42f;

  static const int fa_lambda = 0xf66e;

  static const int fa_lamp = 0xf4ca;

  static const int fa_landmark = 0xf66f;

  static const int fa_landmark_alt = 0xf752;

  static const int fa_language = 0xf1ab;

  static const int fa_laptop = 0xf109;

  static const int fa_laptop_code = 0xf5fc;

  static const int fa_laptop_medical = 0xf812;

  static const int fa_laravel = 0xf3bd;

  static const int fa_lastfm = 0xf202;

  static const int fa_lastfm_square = 0xf203;

  static const int fa_laugh = 0xf599;

  static const int fa_laugh_beam = 0xf59a;

  static const int fa_laugh_squint = 0xf59b;

  static const int fa_laugh_wink = 0xf59c;

  static const int fa_layer_group = 0xf5fd;

  static const int fa_layer_minus = 0xf5fe;

  static const int fa_layer_plus = 0xf5ff;

  static const int fa_leaf = 0xf06c;

  static const int fa_leaf_heart = 0xf4cb;

  static const int fa_leaf_maple = 0xf6f6;

  static const int fa_leaf_oak = 0xf6f7;

  static const int fa_leanpub = 0xf212;

  static const int fa_lemon = 0xf094;

  static const int fa_less = 0xf41d;

  static const int fa_less_than = 0xf536;

  static const int fa_less_than_equal = 0xf537;

  static const int fa_level_down = 0xf149;

  static const int fa_level_down_alt = 0xf3be;

  static const int fa_level_up = 0xf148;

  static const int fa_level_up_alt = 0xf3bf;

  static const int fa_life_ring = 0xf1cd;

  static const int fa_lightbulb = 0xf0eb;

  static const int fa_lightbulb_dollar = 0xf670;

  static const int fa_lightbulb_exclamation = 0xf671;

  static const int fa_lightbulb_on = 0xf672;

  static const int fa_lightbulb_slash = 0xf673;

  static const int fa_lights_holiday = 0xf7b2;

  static const int fa_line = 0xf3c0;

  static const int fa_link = 0xf0c1;

  static const int fa_linkedin = 0xf08c;

  static const int fa_linkedin_in = 0xf0e1;

  static const int fa_linode = 0xf2b8;

  static const int fa_linux = 0xf17c;

  static const int fa_lips = 0xf600;

  static const int fa_lira_sign = 0xf195;

  static const int fa_list = 0xf03a;

  static const int fa_list_alt = 0xf022;

  static const int fa_list_ol = 0xf0cb;

  static const int fa_list_ul = 0xf0ca;

  static const int fa_location = 0xf601;

  static const int fa_location_arrow = 0xf124;

  static const int fa_location_circle = 0xf602;

  static const int fa_location_slash = 0xf603;

  static const int fa_lock = 0xf023;

  static const int fa_lock_alt = 0xf30d;

  static const int fa_lock_open = 0xf3c1;

  static const int fa_lock_open_alt = 0xf3c2;

  static const int fa_long_arrow_alt_down = 0xf309;

  static const int fa_long_arrow_alt_left = 0xf30a;

  static const int fa_long_arrow_alt_right = 0xf30b;

  static const int fa_long_arrow_alt_up = 0xf30c;

  static const int fa_long_arrow_down = 0xf175;

  static const int fa_long_arrow_left = 0xf177;

  static const int fa_long_arrow_right = 0xf178;

  static const int fa_long_arrow_up = 0xf176;

  static const int fa_loveseat = 0xf4cc;

  static const int fa_low_vision = 0xf2a8;

  static const int fa_luchador = 0xf455;

  static const int fa_luggage_cart = 0xf59d;

  static const int fa_lungs = 0xf604;

  static const int fa_lyft = 0xf3c3;

  static const int fa_mace = 0xf6f8;

  static const int fa_magento = 0xf3c4;

  static const int fa_magic = 0xf0d0;

  static const int fa_magnet = 0xf076;

  static const int fa_mail_bulk = 0xf674;

  static const int fa_mailbox = 0xf813;

  static const int fa_mailchimp = 0xf59e;

  static const int fa_male = 0xf183;

  static const int fa_mandalorian = 0xf50f;

  static const int fa_mandolin = 0xf6f9;

  static const int fa_map = 0xf279;

  static const int fa_map_marked = 0xf59f;

  static const int fa_map_marked_alt = 0xf5a0;

  static const int fa_map_marker = 0xf041;

  static const int fa_map_marker_alt = 0xf3c5;

  static const int fa_map_marker_alt_slash = 0xf605;

  static const int fa_map_marker_check = 0xf606;

  static const int fa_map_marker_edit = 0xf607;

  static const int fa_map_marker_exclamation = 0xf608;

  static const int fa_map_marker_minus = 0xf609;

  static const int fa_map_marker_plus = 0xf60a;

  static const int fa_map_marker_question = 0xf60b;

  static const int fa_map_marker_slash = 0xf60c;

  static const int fa_map_marker_smile = 0xf60d;

  static const int fa_map_marker_times = 0xf60e;

  static const int fa_map_pin = 0xf276;

  static const int fa_map_signs = 0xf277;

  static const int fa_markdown = 0xf60f;

  static const int fa_marker = 0xf5a1;

  static const int fa_mars = 0xf222;

  static const int fa_mars_double = 0xf227;

  static const int fa_mars_stroke = 0xf229;

  static const int fa_mars_stroke_h = 0xf22b;

  static const int fa_mars_stroke_v = 0xf22a;

  static const int fa_mask = 0xf6fa;

  static const int fa_mastodon = 0xf4f6;

  static const int fa_maxcdn = 0xf136;

  static const int fa_meat = 0xf814;

  static const int fa_medal = 0xf5a2;

  static const int fa_medapps = 0xf3c6;

  static const int fa_medium = 0xf23a;

  static const int fa_medium_m = 0xf3c7;

  static const int fa_medkit = 0xf0fa;

  static const int fa_medrt = 0xf3c8;

  static const int fa_meetup = 0xf2e0;

  static const int fa_megaphone = 0xf675;

  static const int fa_megaport = 0xf5a3;

  static const int fa_meh = 0xf11a;

  static const int fa_meh_blank = 0xf5a4;

  static const int fa_meh_rolling_eyes = 0xf5a5;

  static const int fa_memory = 0xf538;

  static const int fa_mendeley = 0xf7b3;

  static const int fa_menorah = 0xf676;

  static const int fa_mercury = 0xf223;

  static const int fa_meteor = 0xf753;

  static const int fa_microchip = 0xf2db;

  static const int fa_microphone = 0xf130;

  static const int fa_microphone_alt = 0xf3c9;

  static const int fa_microphone_alt_slash = 0xf539;

  static const int fa_microphone_slash = 0xf131;

  static const int fa_microscope = 0xf610;

  static const int fa_microsoft = 0xf3ca;

  static const int fa_mind_share = 0xf677;

  static const int fa_minus = 0xf068;

  static const int fa_minus_circle = 0xf056;

  static const int fa_minus_hexagon = 0xf307;

  static const int fa_minus_octagon = 0xf308;

  static const int fa_minus_square = 0xf146;

  static const int fa_mistletoe = 0xf7b4;

  static const int fa_mitten = 0xf7b5;

  static const int fa_mix = 0xf3cb;

  static const int fa_mixcloud = 0xf289;

  static const int fa_mizuni = 0xf3cc;

  static const int fa_mobile = 0xf10b;

  static const int fa_mobile_alt = 0xf3cd;

  static const int fa_mobile_android = 0xf3ce;

  static const int fa_mobile_android_alt = 0xf3cf;

  static const int fa_modx = 0xf285;

  static const int fa_monero = 0xf3d0;

  static const int fa_money_bill = 0xf0d6;

  static const int fa_money_bill_alt = 0xf3d1;

  static const int fa_money_bill_wave = 0xf53a;

  static const int fa_money_bill_wave_alt = 0xf53b;

  static const int fa_money_check = 0xf53c;

  static const int fa_money_check_alt = 0xf53d;

  static const int fa_monitor_heart_rate = 0xf611;

  static const int fa_monkey = 0xf6fb;

  static const int fa_monument = 0xf5a6;

  static const int fa_moon = 0xf186;

  static const int fa_moon_cloud = 0xf754;

  static const int fa_moon_stars = 0xf755;

  static const int fa_mortar_pestle = 0xf5a7;

  static const int fa_mosque = 0xf678;

  static const int fa_motorcycle = 0xf21c;

  static const int fa_mountain = 0xf6fc;

  static const int fa_mountains = 0xf6fd;

  static const int fa_mouse_pointer = 0xf245;

  static const int fa_mug_hot = 0xf7b6;

  static const int fa_mug_marshmallows = 0xf7b7;

  static const int fa_music = 0xf001;

  static const int fa_napster = 0xf3d2;

  static const int fa_narwhal = 0xf6fe;

  static const int fa_neos = 0xf612;

  static const int fa_network_wired = 0xf6ff;

  static const int fa_neuter = 0xf22c;

  static const int fa_newspaper = 0xf1ea;

  static const int fa_nimblr = 0xf5a8;

  static const int fa_nintendo_switch = 0xf418;

  static const int fa_node = 0xf419;

  static const int fa_node_js = 0xf3d3;

  static const int fa_not_equal = 0xf53e;

  static const int fa_notes_medical = 0xf481;

  static const int fa_npm = 0xf3d4;

  static const int fa_ns8 = 0xf3d5;

  static const int fa_nutritionix = 0xf3d6;

  static const int fa_object_group = 0xf247;

  static const int fa_object_ungroup = 0xf248;

  static const int fa_octagon = 0xf306;

  static const int fa_odnoklassniki = 0xf263;

  static const int fa_odnoklassniki_square = 0xf264;

  static const int fa_oil_can = 0xf613;

  static const int fa_oil_temp = 0xf614;

  static const int fa_old_republic = 0xf510;

  static const int fa_om = 0xf679;

  static const int fa_omega = 0xf67a;

  static const int fa_opencart = 0xf23d;

  static const int fa_openid = 0xf19b;

  static const int fa_opera = 0xf26a;

  static const int fa_optin_monster = 0xf23c;

  static const int fa_ornament = 0xf7b8;

  static const int fa_osi = 0xf41a;

  static const int fa_otter = 0xf700;

  static const int fa_outdent = 0xf03b;

  static const int fa_page4 = 0xf3d7;

  static const int fa_pagelines = 0xf18c;

  static const int fa_pager = 0xf815;

  static const int fa_paint_brush = 0xf1fc;

  static const int fa_paint_brush_alt = 0xf5a9;

  static const int fa_paint_roller = 0xf5aa;

  static const int fa_palette = 0xf53f;

  static const int fa_palfed = 0xf3d8;

  static const int fa_pallet = 0xf482;

  static const int fa_pallet_alt = 0xf483;

  static const int fa_paper_plane = 0xf1d8;

  static const int fa_paperclip = 0xf0c6;

  static const int fa_parachute_box = 0xf4cd;

  static const int fa_paragraph = 0xf1dd;

  static const int fa_parking = 0xf540;

  static const int fa_parking_circle = 0xf615;

  static const int fa_parking_circle_slash = 0xf616;

  static const int fa_parking_slash = 0xf617;

  static const int fa_passport = 0xf5ab;

  static const int fa_pastafarianism = 0xf67b;

  static const int fa_paste = 0xf0ea;

  static const int fa_patreon = 0xf3d9;

  static const int fa_pause = 0xf04c;

  static const int fa_pause_circle = 0xf28b;

  static const int fa_paw = 0xf1b0;

  static const int fa_paw_alt = 0xf701;

  static const int fa_paw_claws = 0xf702;

  static const int fa_paypal = 0xf1ed;

  static const int fa_peace = 0xf67c;

  static const int fa_pegasus = 0xf703;

  static const int fa_pen = 0xf304;

  static const int fa_pen_alt = 0xf305;

  static const int fa_pen_fancy = 0xf5ac;

  static const int fa_pen_nib = 0xf5ad;

  static const int fa_pen_square = 0xf14b;

  static const int fa_pencil = 0xf040;

  static const int fa_pencil_alt = 0xf303;

  static const int fa_pencil_paintbrush = 0xf618;

  static const int fa_pencil_ruler = 0xf5ae;

  static const int fa_pennant = 0xf456;

  static const int fa_penny_arcade = 0xf704;

  static const int fa_people_carry = 0xf4ce;

  static const int fa_pepper_hot = 0xf816;

  static const int fa_percent = 0xf295;

  static const int fa_percentage = 0xf541;

  static const int fa_periscope = 0xf3da;

  static const int fa_person_booth = 0xf756;

  static const int fa_person_carry = 0xf4cf;

  static const int fa_person_dolly = 0xf4d0;

  static const int fa_person_dolly_empty = 0xf4d1;

  static const int fa_person_sign = 0xf757;

  static const int fa_phabricator = 0xf3db;

  static const int fa_phoenix_framework = 0xf3dc;

  static const int fa_phoenix_squadron = 0xf511;

  static const int fa_phone = 0xf095;

  static const int fa_phone_office = 0xf67d;

  static const int fa_phone_plus = 0xf4d2;

  static const int fa_phone_slash = 0xf3dd;

  static const int fa_phone_square = 0xf098;

  static const int fa_phone_volume = 0xf2a0;

  static const int fa_php = 0xf457;

  static const int fa_pi = 0xf67e;

  static const int fa_pie = 0xf705;

  static const int fa_pied_piper = 0xf2ae;

  static const int fa_pied_piper_alt = 0xf1a8;

  static const int fa_pied_piper_hat = 0xf4e5;

  static const int fa_pied_piper_pp = 0xf1a7;

  static const int fa_pig = 0xf706;

  static const int fa_piggy_bank = 0xf4d3;

  static const int fa_pills = 0xf484;

  static const int fa_pinterest = 0xf0d2;

  static const int fa_pinterest_p = 0xf231;

  static const int fa_pinterest_square = 0xf0d3;

  static const int fa_pizza = 0xf817;

  static const int fa_pizza_slice = 0xf818;

  static const int fa_place_of_worship = 0xf67f;

  static const int fa_plane = 0xf072;

  static const int fa_plane_alt = 0xf3de;

  static const int fa_plane_arrival = 0xf5af;

  static const int fa_plane_departure = 0xf5b0;

  static const int fa_play = 0xf04b;

  static const int fa_play_circle = 0xf144;

  static const int fa_playstation = 0xf3df;

  static const int fa_plug = 0xf1e6;

  static const int fa_plus = 0xf067;

  static const int fa_plus_circle = 0xf055;

  static const int fa_plus_hexagon = 0xf300;

  static const int fa_plus_octagon = 0xf301;

  static const int fa_plus_square = 0xf0fe;

  static const int fa_podcast = 0xf2ce;

  static const int fa_podium = 0xf680;

  static const int fa_podium_star = 0xf758;

  static const int fa_poll = 0xf681;

  static const int fa_poll_h = 0xf682;

  static const int fa_poll_people = 0xf759;

  static const int fa_poo = 0xf2fe;

  static const int fa_poo_storm = 0xf75a;

  static const int fa_poop = 0xf619;

  static const int fa_popcorn = 0xf819;

  static const int fa_portrait = 0xf3e0;

  static const int fa_pound_sign = 0xf154;

  static const int fa_power_off = 0xf011;

  static const int fa_pray = 0xf683;

  static const int fa_praying_hands = 0xf684;

  static const int fa_prescription = 0xf5b1;

  static const int fa_prescription_bottle = 0xf485;

  static const int fa_prescription_bottle_alt = 0xf486;

  static const int fa_presentation = 0xf685;

  static const int fa_print = 0xf02f;

  static const int fa_print_search = 0xf81a;

  static const int fa_print_slash = 0xf686;

  static const int fa_procedures = 0xf487;

  static const int fa_product_hunt = 0xf288;

  static const int fa_project_diagram = 0xf542;

  static const int fa_pumpkin = 0xf707;

  static const int fa_pushed = 0xf3e1;

  static const int fa_puzzle_piece = 0xf12e;

  static const int fa_python = 0xf3e2;

  static const int fa_qq = 0xf1d6;

  static const int fa_qrcode = 0xf029;

  static const int fa_question = 0xf128;

  static const int fa_question_circle = 0xf059;

  static const int fa_question_square = 0xf2fd;

  static const int fa_quidditch = 0xf458;

  static const int fa_quinscape = 0xf459;

  static const int fa_quora = 0xf2c4;

  static const int fa_quote_left = 0xf10d;

  static const int fa_quote_right = 0xf10e;

  static const int fa_quran = 0xf687;

  static const int fa_r_project = 0xf4f7;

  static const int fa_rabbit = 0xf708;

  static const int fa_rabbit_fast = 0xf709;

  static const int fa_racquet = 0xf45a;

  static const int fa_radiation = 0xf7b9;

  static const int fa_radiation_alt = 0xf7ba;

  static const int fa_rainbow = 0xf75b;

  static const int fa_raindrops = 0xf75c;

  static const int fa_ram = 0xf70a;

  static const int fa_ramp_loading = 0xf4d4;

  static const int fa_random = 0xf074;

  static const int fa_raspberry_pi = 0xf7bb;

  static const int fa_ravelry = 0xf2d9;

  static const int fa_react = 0xf41b;

  static const int fa_reacteurope = 0xf75d;

  static const int fa_readme = 0xf4d5;

  static const int fa_rebel = 0xf1d0;

  static const int fa_receipt = 0xf543;

  static const int fa_rectangle_landscape = 0xf2fa;

  static const int fa_rectangle_portrait = 0xf2fb;

  static const int fa_rectangle_wide = 0xf2fc;

  static const int fa_recycle = 0xf1b8;

  static const int fa_red_river = 0xf3e3;

  static const int fa_reddit = 0xf1a1;

  static const int fa_reddit_alien = 0xf281;

  static const int fa_reddit_square = 0xf1a2;

  static const int fa_redhat = 0xf7bc;

  static const int fa_redo = 0xf01e;

  static const int fa_redo_alt = 0xf2f9;

  static const int fa_registered = 0xf25d;

  static const int fa_renren = 0xf18b;

  static const int fa_repeat = 0xf363;

  static const int fa_repeat_1 = 0xf365;

  static const int fa_repeat_1_alt = 0xf366;

  static const int fa_repeat_alt = 0xf364;

  static const int fa_reply = 0xf3e5;

  static const int fa_reply_all = 0xf122;

  static const int fa_replyd = 0xf3e6;

  static const int fa_republican = 0xf75e;

  static const int fa_researchgate = 0xf4f8;

  static const int fa_resolving = 0xf3e7;

  static const int fa_restroom = 0xf7bd;

  static const int fa_retweet = 0xf079;

  static const int fa_retweet_alt = 0xf361;

  static const int fa_rev = 0xf5b2;

  static const int fa_ribbon = 0xf4d6;

  static const int fa_ring = 0xf70b;

  static const int fa_rings_wedding = 0xf81b;

  static const int fa_road = 0xf018;

  static const int fa_robot = 0xf544;

  static const int fa_rocket = 0xf135;

  static const int fa_rocketchat = 0xf3e8;

  static const int fa_rockrms = 0xf3e9;

  static const int fa_route = 0xf4d7;

  static const int fa_route_highway = 0xf61a;

  static const int fa_route_interstate = 0xf61b;

  static const int fa_rss = 0xf09e;

  static const int fa_rss_square = 0xf143;

  static const int fa_ruble_sign = 0xf158;

  static const int fa_ruler = 0xf545;

  static const int fa_ruler_combined = 0xf546;

  static const int fa_ruler_horizontal = 0xf547;

  static const int fa_ruler_triangle = 0xf61c;

  static const int fa_ruler_vertical = 0xf548;

  static const int fa_running = 0xf70c;

  static const int fa_rupee_sign = 0xf156;

  static const int fa_rv = 0xf7be;

  static const int fa_sack = 0xf81c;

  static const int fa_sack_dollar = 0xf81d;

  static const int fa_sad_cry = 0xf5b3;

  static const int fa_sad_tear = 0xf5b4;

  static const int fa_safari = 0xf267;

  static const int fa_salad = 0xf81e;

  static const int fa_salesforce = 0xf83b;

  static const int fa_sandwich = 0xf81f;

  static const int fa_sass = 0xf41e;

  static const int fa_satellite = 0xf7bf;

  static const int fa_satellite_dish = 0xf7c0;

  static const int fa_sausage = 0xf820;

  static const int fa_save = 0xf0c7;

  static const int fa_scalpel = 0xf61d;

  static const int fa_scalpel_path = 0xf61e;

  static const int fa_scanner = 0xf488;

  static const int fa_scanner_keyboard = 0xf489;

  static const int fa_scanner_touchscreen = 0xf48a;

  static const int fa_scarecrow = 0xf70d;

  static const int fa_scarf = 0xf7c1;

  static const int fa_schlix = 0xf3ea;

  static const int fa_school = 0xf549;

  static const int fa_screwdriver = 0xf54a;

  static const int fa_scribd = 0xf28a;

  static const int fa_scroll = 0xf70e;

  static const int fa_scroll_old = 0xf70f;

  static const int fa_scrubber = 0xf2f8;

  static const int fa_scythe = 0xf710;

  static const int fa_sd_card = 0xf7c2;

  static const int fa_search = 0xf002;

  static const int fa_search_dollar = 0xf688;

  static const int fa_search_location = 0xf689;

  static const int fa_search_minus = 0xf010;

  static const int fa_search_plus = 0xf00e;

  static const int fa_searchengin = 0xf3eb;

  static const int fa_seedling = 0xf4d8;

  static const int fa_sellcast = 0xf2da;

  static const int fa_sellsy = 0xf213;

  static const int fa_server = 0xf233;

  static const int fa_servicestack = 0xf3ec;

  static const int fa_shapes = 0xf61f;

  static const int fa_share = 0xf064;

  static const int fa_share_all = 0xf367;

  static const int fa_share_alt = 0xf1e0;

  static const int fa_share_alt_square = 0xf1e1;

  static const int fa_share_square = 0xf14d;

  static const int fa_sheep = 0xf711;

  static const int fa_shekel_sign = 0xf20b;

  static const int fa_shield = 0xf132;

  static const int fa_shield_alt = 0xf3ed;

  static const int fa_shield_check = 0xf2f7;

  static const int fa_shield_cross = 0xf712;

  static const int fa_ship = 0xf21a;

  static const int fa_shipping_fast = 0xf48b;

  static const int fa_shipping_timed = 0xf48c;

  static const int fa_shirtsinbulk = 0xf214;

  static const int fa_shish_kebab = 0xf821;

  static const int fa_shoe_prints = 0xf54b;

  static const int fa_shopping_bag = 0xf290;

  static const int fa_shopping_basket = 0xf291;

  static const int fa_shopping_cart = 0xf07a;

  static const int fa_shopware = 0xf5b5;

  static const int fa_shovel = 0xf713;

  static const int fa_shovel_snow = 0xf7c3;

  static const int fa_shower = 0xf2cc;

  static const int fa_shredder = 0xf68a;

  static const int fa_shuttle_van = 0xf5b6;

  static const int fa_shuttlecock = 0xf45b;

  static const int fa_sickle = 0xf822;

  static const int fa_sigma = 0xf68b;

  static const int fa_sign = 0xf4d9;

  static const int fa_sign_in = 0xf090;

  static const int fa_sign_in_alt = 0xf2f6;

  static const int fa_sign_language = 0xf2a7;

  static const int fa_sign_out = 0xf08b;

  static const int fa_sign_out_alt = 0xf2f5;

  static const int fa_signal = 0xf012;

  static const int fa_signal_1 = 0xf68c;

  static const int fa_signal_2 = 0xf68d;

  static const int fa_signal_3 = 0xf68e;

  static const int fa_signal_4 = 0xf68f;

  static const int fa_signal_alt = 0xf690;

  static const int fa_signal_alt_1 = 0xf691;

  static const int fa_signal_alt_2 = 0xf692;

  static const int fa_signal_alt_3 = 0xf693;

  static const int fa_signal_alt_slash = 0xf694;

  static const int fa_signal_slash = 0xf695;

  static const int fa_signature = 0xf5b7;

  static const int fa_sim_card = 0xf7c4;

  static const int fa_simplybuilt = 0xf215;

  static const int fa_sistrix = 0xf3ee;

  static const int fa_sitemap = 0xf0e8;

  static const int fa_sith = 0xf512;

  static const int fa_skating = 0xf7c5;

  static const int fa_skeleton = 0xf620;

  static const int fa_sketch = 0xf7c6;

  static const int fa_ski_jump = 0xf7c7;

  static const int fa_ski_lift = 0xf7c8;

  static const int fa_skiing = 0xf7c9;

  static const int fa_skiing_nordic = 0xf7ca;

  static const int fa_skull = 0xf54c;

  static const int fa_skull_crossbones = 0xf714;

  static const int fa_skyatlas = 0xf216;

  static const int fa_skype = 0xf17e;

  static const int fa_slack = 0xf198;

  static const int fa_slack_hash = 0xf3ef;

  static const int fa_slash = 0xf715;

  static const int fa_sledding = 0xf7cb;

  static const int fa_sleigh = 0xf7cc;

  static const int fa_sliders_h = 0xf1de;

  static const int fa_sliders_h_square = 0xf3f0;

  static const int fa_sliders_v = 0xf3f1;

  static const int fa_sliders_v_square = 0xf3f2;

  static const int fa_slideshare = 0xf1e7;

  static const int fa_smile = 0xf118;

  static const int fa_smile_beam = 0xf5b8;

  static const int fa_smile_plus = 0xf5b9;

  static const int fa_smile_wink = 0xf4da;

  static const int fa_smog = 0xf75f;

  static const int fa_smoke = 0xf760;

  static const int fa_smoking = 0xf48d;

  static const int fa_smoking_ban = 0xf54d;

  static const int fa_sms = 0xf7cd;

  static const int fa_snake = 0xf716;

  static const int fa_snapchat = 0xf2ab;

  static const int fa_snapchat_ghost = 0xf2ac;

  static const int fa_snapchat_square = 0xf2ad;

  static const int fa_snow_blowing = 0xf761;

  static const int fa_snowboarding = 0xf7ce;

  static const int fa_snowflake = 0xf2dc;

  static const int fa_snowflakes = 0xf7cf;

  static const int fa_snowman = 0xf7d0;

  static const int fa_snowmobile = 0xf7d1;

  static const int fa_snowplow = 0xf7d2;

  static const int fa_socks = 0xf696;

  static const int fa_solar_panel = 0xf5ba;

  static const int fa_sort = 0xf0dc;

  static const int fa_sort_alpha_down = 0xf15d;

  static const int fa_sort_alpha_up = 0xf15e;

  static const int fa_sort_amount_down = 0xf160;

  static const int fa_sort_amount_up = 0xf161;

  static const int fa_sort_down = 0xf0dd;

  static const int fa_sort_numeric_down = 0xf162;

  static const int fa_sort_numeric_up = 0xf163;

  static const int fa_sort_up = 0xf0de;

  static const int fa_soundcloud = 0xf1be;

  static const int fa_soup = 0xf823;

  static const int fa_sourcetree = 0xf7d3;

  static const int fa_spa = 0xf5bb;

  static const int fa_space_shuttle = 0xf197;

  static const int fa_spade = 0xf2f4;

  static const int fa_speakap = 0xf3f3;

  static const int fa_speaker_deck = 0xf83c;

  static const int fa_spider = 0xf717;

  static const int fa_spider_black_widow = 0xf718;

  static const int fa_spider_web = 0xf719;

  static const int fa_spinner = 0xf110;

  static const int fa_spinner_third = 0xf3f4;

  static const int fa_splotch = 0xf5bc;

  static const int fa_spotify = 0xf1bc;

  static const int fa_spray_can = 0xf5bd;

  static const int fa_square = 0xf0c8;

  static const int fa_square_full = 0xf45c;

  static const int fa_square_root = 0xf697;

  static const int fa_square_root_alt = 0xf698;

  static const int fa_squarespace = 0xf5be;

  static const int fa_squirrel = 0xf71a;

  static const int fa_stack_exchange = 0xf18d;

  static const int fa_stack_overflow = 0xf16c;

  static const int fa_staff = 0xf71b;

  static const int fa_stamp = 0xf5bf;

  static const int fa_star = 0xf005;

  static const int fa_star_and_crescent = 0xf699;

  static const int fa_star_christmas = 0xf7d4;

  static const int fa_star_exclamation = 0xf2f3;

  static const int fa_star_half = 0xf089;

  static const int fa_star_half_alt = 0xf5c0;

  static const int fa_star_of_david = 0xf69a;

  static const int fa_star_of_life = 0xf621;

  static const int fa_stars = 0xf762;

  static const int fa_staylinked = 0xf3f5;

  static const int fa_steak = 0xf824;

  static const int fa_steam = 0xf1b6;

  static const int fa_steam_square = 0xf1b7;

  static const int fa_steam_symbol = 0xf3f6;

  static const int fa_steering_wheel = 0xf622;

  static const int fa_step_backward = 0xf048;

  static const int fa_step_forward = 0xf051;

  static const int fa_stethoscope = 0xf0f1;

  static const int fa_sticker_mule = 0xf3f7;

  static const int fa_sticky_note = 0xf249;

  static const int fa_stocking = 0xf7d5;

  static const int fa_stomach = 0xf623;

  static const int fa_stop = 0xf04d;

  static const int fa_stop_circle = 0xf28d;

  static const int fa_stopwatch = 0xf2f2;

  static const int fa_store = 0xf54e;

  static const int fa_store_alt = 0xf54f;

  static const int fa_strava = 0xf428;

  static const int fa_stream = 0xf550;

  static const int fa_street_view = 0xf21d;

  static const int fa_stretcher = 0xf825;

  static const int fa_strikethrough = 0xf0cc;

  static const int fa_stripe = 0xf429;

  static const int fa_stripe_s = 0xf42a;

  static const int fa_stroopwafel = 0xf551;

  static const int fa_studiovinari = 0xf3f8;

  static const int fa_stumbleupon = 0xf1a4;

  static const int fa_stumbleupon_circle = 0xf1a3;

  static const int fa_subscript = 0xf12c;

  static const int fa_subway = 0xf239;

  static const int fa_suitcase = 0xf0f2;

  static const int fa_suitcase_rolling = 0xf5c1;

  static const int fa_sun = 0xf185;

  static const int fa_sun_cloud = 0xf763;

  static const int fa_sun_dust = 0xf764;

  static const int fa_sun_haze = 0xf765;

  static const int fa_sunrise = 0xf766;

  static const int fa_sunset = 0xf767;

  static const int fa_superpowers = 0xf2dd;

  static const int fa_superscript = 0xf12b;

  static const int fa_supple = 0xf3f9;

  static const int fa_surprise = 0xf5c2;

  static const int fa_suse = 0xf7d6;

  static const int fa_swatchbook = 0xf5c3;

  static const int fa_swimmer = 0xf5c4;

  static const int fa_swimming_pool = 0xf5c5;

  static const int fa_sword = 0xf71c;

  static const int fa_swords = 0xf71d;

  static const int fa_symfony = 0xf83d;

  static const int fa_synagogue = 0xf69b;

  static const int fa_sync = 0xf021;

  static const int fa_sync_alt = 0xf2f1;

  static const int fa_syringe = 0xf48e;

  static const int fa_table = 0xf0ce;

  static const int fa_table_tennis = 0xf45d;

  static const int fa_tablet = 0xf10a;

  static const int fa_tablet_alt = 0xf3fa;

  static const int fa_tablet_android = 0xf3fb;

  static const int fa_tablet_android_alt = 0xf3fc;

  static const int fa_tablet_rugged = 0xf48f;

  static const int fa_tablets = 0xf490;

  static const int fa_tachometer = 0xf0e4;

  static const int fa_tachometer_alt = 0xf3fd;

  static const int fa_tachometer_alt_average = 0xf624;

  static const int fa_tachometer_alt_fast = 0xf625;

  static const int fa_tachometer_alt_fastest = 0xf626;

  static const int fa_tachometer_alt_slow = 0xf627;

  static const int fa_tachometer_alt_slowest = 0xf628;

  static const int fa_tachometer_average = 0xf629;

  static const int fa_tachometer_fast = 0xf62a;

  static const int fa_tachometer_fastest = 0xf62b;

  static const int fa_tachometer_slow = 0xf62c;

  static const int fa_tachometer_slowest = 0xf62d;

  static const int fa_taco = 0xf826;

  static const int fa_tag = 0xf02b;

  static const int fa_tags = 0xf02c;

  static const int fa_tally = 0xf69c;

  static const int fa_tanakh = 0xf827;

  static const int fa_tape = 0xf4db;

  static const int fa_tasks = 0xf0ae;

  static const int fa_tasks_alt = 0xf828;

  static const int fa_taxi = 0xf1ba;

  static const int fa_teamspeak = 0xf4f9;

  static const int fa_teeth = 0xf62e;

  static const int fa_teeth_open = 0xf62f;

  static const int fa_telegram = 0xf2c6;

  static const int fa_telegram_plane = 0xf3fe;

  static const int fa_temperature_frigid = 0xf768;

  static const int fa_temperature_high = 0xf769;

  static const int fa_temperature_hot = 0xf76a;

  static const int fa_temperature_low = 0xf76b;

  static const int fa_tencent_weibo = 0xf1d5;

  static const int fa_tenge = 0xf7d7;

  static const int fa_tennis_ball = 0xf45e;

  static const int fa_terminal = 0xf120;

  static const int fa_text_height = 0xf034;

  static const int fa_text_width = 0xf035;

  static const int fa_th = 0xf00a;

  static const int fa_th_large = 0xf009;

  static const int fa_th_list = 0xf00b;

  static const int fa_the_red_yeti = 0xf69d;

  static const int fa_theater_masks = 0xf630;

  static const int fa_themeco = 0xf5c6;

  static const int fa_themeisle = 0xf2b2;

  static const int fa_thermometer = 0xf491;

  static const int fa_thermometer_empty = 0xf2cb;

  static const int fa_thermometer_full = 0xf2c7;

  static const int fa_thermometer_half = 0xf2c9;

  static const int fa_thermometer_quarter = 0xf2ca;

  static const int fa_thermometer_three_quarters = 0xf2c8;

  static const int fa_theta = 0xf69e;

  static const int fa_think_peaks = 0xf731;

  static const int fa_thumbs_down = 0xf165;

  static const int fa_thumbs_up = 0xf164;

  static const int fa_thumbtack = 0xf08d;

  static const int fa_thunderstorm = 0xf76c;

  static const int fa_thunderstorm_moon = 0xf76d;

  static const int fa_thunderstorm_sun = 0xf76e;

  static const int fa_ticket = 0xf145;

  static const int fa_ticket_alt = 0xf3ff;

  static const int fa_tilde = 0xf69f;

  static const int fa_times = 0xf00d;

  static const int fa_times_circle = 0xf057;

  static const int fa_times_hexagon = 0xf2ee;

  static const int fa_times_octagon = 0xf2f0;

  static const int fa_times_square = 0xf2d3;

  static const int fa_tint = 0xf043;

  static const int fa_tint_slash = 0xf5c7;

  static const int fa_tire = 0xf631;

  static const int fa_tire_flat = 0xf632;

  static const int fa_tire_pressure_warning = 0xf633;

  static const int fa_tire_rugged = 0xf634;

  static const int fa_tired = 0xf5c8;

  static const int fa_toggle_off = 0xf204;

  static const int fa_toggle_on = 0xf205;

  static const int fa_toilet = 0xf7d8;

  static const int fa_toilet_paper = 0xf71e;

  static const int fa_toilet_paper_alt = 0xf71f;

  static const int fa_tombstone = 0xf720;

  static const int fa_tombstone_alt = 0xf721;

  static const int fa_toolbox = 0xf552;

  static const int fa_tools = 0xf7d9;

  static const int fa_tooth = 0xf5c9;

  static const int fa_toothbrush = 0xf635;

  static const int fa_torah = 0xf6a0;

  static const int fa_torii_gate = 0xf6a1;

  static const int fa_tornado = 0xf76f;

  static const int fa_tractor = 0xf722;

  static const int fa_trade_federation = 0xf513;

  static const int fa_trademark = 0xf25c;

  static const int fa_traffic_cone = 0xf636;

  static const int fa_traffic_light = 0xf637;

  static const int fa_traffic_light_go = 0xf638;

  static const int fa_traffic_light_slow = 0xf639;

  static const int fa_traffic_light_stop = 0xf63a;

  static const int fa_train = 0xf238;

  static const int fa_tram = 0xf7da;

  static const int fa_transgender = 0xf224;

  static const int fa_transgender_alt = 0xf225;

  static const int fa_trash = 0xf1f8;

  static const int fa_trash_alt = 0xf2ed;

  static const int fa_trash_restore = 0xf829;

  static const int fa_trash_restore_alt = 0xf82a;

  static const int fa_treasure_chest = 0xf723;

  static const int fa_tree = 0xf1bb;

  static const int fa_tree_alt = 0xf400;

  static const int fa_tree_christmas = 0xf7db;

  static const int fa_tree_decorated = 0xf7dc;

  static const int fa_tree_large = 0xf7dd;

  static const int fa_tree_palm = 0xf82b;

  static const int fa_trees = 0xf724;

  static const int fa_trello = 0xf181;

  static const int fa_triangle = 0xf2ec;

  static const int fa_tripadvisor = 0xf262;

  static const int fa_trophy = 0xf091;

  static const int fa_trophy_alt = 0xf2eb;

  static const int fa_truck = 0xf0d1;

  static const int fa_truck_container = 0xf4dc;

  static const int fa_truck_couch = 0xf4dd;

  static const int fa_truck_loading = 0xf4de;

  static const int fa_truck_monster = 0xf63b;

  static const int fa_truck_moving = 0xf4df;

  static const int fa_truck_pickup = 0xf63c;

  static const int fa_truck_plow = 0xf7de;

  static const int fa_truck_ramp = 0xf4e0;

  static const int fa_tshirt = 0xf553;

  static const int fa_tty = 0xf1e4;

  static const int fa_tumblr = 0xf173;

  static const int fa_tumblr_square = 0xf174;

  static const int fa_turkey = 0xf725;

  static const int fa_turtle = 0xf726;

  static const int fa_tv = 0xf26c;

  static const int fa_tv_retro = 0xf401;

  static const int fa_twitch = 0xf1e8;

  static const int fa_twitter = 0xf099;

  static const int fa_twitter_square = 0xf081;

  static const int fa_typo3 = 0xf42b;

  static const int fa_uber = 0xf402;

  static const int fa_ubuntu = 0xf7df;

  static const int fa_uikit = 0xf403;

  static const int fa_umbrella = 0xf0e9;

  static const int fa_umbrella_beach = 0xf5ca;

  static const int fa_underline = 0xf0cd;

  static const int fa_undo = 0xf0e2;

  static const int fa_undo_alt = 0xf2ea;

  static const int fa_unicorn = 0xf727;

  static const int fa_union = 0xf6a2;

  static const int fa_uniregistry = 0xf404;

  static const int fa_universal_access = 0xf29a;

  static const int fa_university = 0xf19c;

  static const int fa_unlink = 0xf127;

  static const int fa_unlock = 0xf09c;

  static const int fa_unlock_alt = 0xf13e;

  static const int fa_untappd = 0xf405;

  static const int fa_upload = 0xf093;

  static const int fa_ups = 0xf7e0;

  static const int fa_usb = 0xf287;

  static const int fa_usd_circle = 0xf2e8;

  static const int fa_usd_square = 0xf2e9;

  static const int fa_user = 0xf007;

  static const int fa_user_alt = 0xf406;

  static const int fa_user_alt_slash = 0xf4fa;

  static const int fa_user_astronaut = 0xf4fb;

  static const int fa_user_chart = 0xf6a3;

  static const int fa_user_check = 0xf4fc;

  static const int fa_user_circle = 0xf2bd;

  static const int fa_user_clock = 0xf4fd;

  static const int fa_user_cog = 0xf4fe;

  static const int fa_user_crown = 0xf6a4;

  static const int fa_user_edit = 0xf4ff;

  static const int fa_user_friends = 0xf500;

  static const int fa_user_graduate = 0xf501;

  static const int fa_user_hard_hat = 0xf82c;

  static const int fa_user_headset = 0xf82d;

  static const int fa_user_injured = 0xf728;

  static const int fa_user_lock = 0xf502;

  static const int fa_user_md = 0xf0f0;

  static const int fa_user_md_chat = 0xf82e;

  static const int fa_user_minus = 0xf503;

  static const int fa_user_ninja = 0xf504;

  static const int fa_user_nurse = 0xf82f;

  static const int fa_user_plus = 0xf234;

  static const int fa_user_secret = 0xf21b;

  static const int fa_user_shield = 0xf505;

  static const int fa_user_slash = 0xf506;

  static const int fa_user_tag = 0xf507;

  static const int fa_user_tie = 0xf508;

  static const int fa_user_times = 0xf235;

  static const int fa_users = 0xf0c0;

  static const int fa_users_class = 0xf63d;

  static const int fa_users_cog = 0xf509;

  static const int fa_users_crown = 0xf6a5;

  static const int fa_users_medical = 0xf830;

  static const int fa_usps = 0xf7e1;

  static const int fa_ussunnah = 0xf407;

  static const int fa_utensil_fork = 0xf2e3;

  static const int fa_utensil_knife = 0xf2e4;

  static const int fa_utensil_spoon = 0xf2e5;

  static const int fa_utensils = 0xf2e7;

  static const int fa_utensils_alt = 0xf2e6;

  static const int fa_vaadin = 0xf408;

  static const int fa_value_absolute = 0xf6a6;

  static const int fa_vector_square = 0xf5cb;

  static const int fa_venus = 0xf221;

  static const int fa_venus_double = 0xf226;

  static const int fa_venus_mars = 0xf228;

  static const int fa_viacoin = 0xf237;

  static const int fa_viadeo = 0xf2a9;

  static const int fa_viadeo_square = 0xf2aa;

  static const int fa_vial = 0xf492;

  static const int fa_vials = 0xf493;

  static const int fa_viber = 0xf409;

  static const int fa_video = 0xf03d;

  static const int fa_video_plus = 0xf4e1;

  static const int fa_video_slash = 0xf4e2;

  static const int fa_vihara = 0xf6a7;

  static const int fa_vimeo = 0xf40a;

  static const int fa_vimeo_square = 0xf194;

  static const int fa_vimeo_v = 0xf27d;

  static const int fa_vine = 0xf1ca;

  static const int fa_vk = 0xf189;

  static const int fa_vnv = 0xf40b;

  static const int fa_volcano = 0xf770;

  static const int fa_volleyball_ball = 0xf45f;

  static const int fa_volume = 0xf6a8;

  static const int fa_volume_down = 0xf027;

  static const int fa_volume_mute = 0xf6a9;

  static const int fa_volume_off = 0xf026;

  static const int fa_volume_slash = 0xf2e2;

  static const int fa_volume_up = 0xf028;

  static const int fa_vote_nay = 0xf771;

  static const int fa_vote_yea = 0xf772;

  static const int fa_vr_cardboard = 0xf729;

  static const int fa_vuejs = 0xf41f;

  static const int fa_walker = 0xf831;

  static const int fa_walking = 0xf554;

  static const int fa_wallet = 0xf555;

  static const int fa_wand = 0xf72a;

  static const int fa_wand_magic = 0xf72b;

  static const int fa_warehouse = 0xf494;

  static const int fa_warehouse_alt = 0xf495;

  static const int fa_watch = 0xf2e1;

  static const int fa_watch_fitness = 0xf63e;

  static const int fa_water = 0xf773;

  static const int fa_water_lower = 0xf774;

  static const int fa_water_rise = 0xf775;

  static const int fa_wave_square = 0xf83e;

  static const int fa_waze = 0xf83f;

  static const int fa_webcam = 0xf832;

  static const int fa_webcam_slash = 0xf833;

  static const int fa_weebly = 0xf5cc;

  static const int fa_weibo = 0xf18a;

  static const int fa_weight = 0xf496;

  static const int fa_weight_hanging = 0xf5cd;

  static const int fa_weixin = 0xf1d7;

  static const int fa_whale = 0xf72c;

  static const int fa_whatsapp = 0xf232;

  static const int fa_whatsapp_square = 0xf40c;

  static const int fa_wheat = 0xf72d;

  static const int fa_wheelchair = 0xf193;

  static const int fa_whistle = 0xf460;

  static const int fa_whmcs = 0xf40d;

  static const int fa_wifi = 0xf1eb;

  static const int fa_wifi_1 = 0xf6aa;

  static const int fa_wifi_2 = 0xf6ab;

  static const int fa_wifi_slash = 0xf6ac;

  static const int fa_wikipedia_w = 0xf266;

  static const int fa_wind = 0xf72e;

  static const int fa_wind_warning = 0xf776;

  static const int fa_window = 0xf40e;

  static const int fa_window_alt = 0xf40f;

  static const int fa_window_close = 0xf410;

  static const int fa_window_maximize = 0xf2d0;

  static const int fa_window_minimize = 0xf2d1;

  static const int fa_window_restore = 0xf2d2;

  static const int fa_windows = 0xf17a;

  static const int fa_windsock = 0xf777;

  static const int fa_wine_bottle = 0xf72f;

  static const int fa_wine_glass = 0xf4e3;

  static const int fa_wine_glass_alt = 0xf5ce;

  static const int fa_wix = 0xf5cf;

  static const int fa_wizards_of_the_coast = 0xf730;

  static const int fa_wolf_pack_battalion = 0xf514;

  static const int fa_won_sign = 0xf159;

  static const int fa_wordpress = 0xf19a;

  static const int fa_wordpress_simple = 0xf411;

  static const int fa_wpbeginner = 0xf297;

  static const int fa_wpexplorer = 0xf2de;

  static const int fa_wpforms = 0xf298;

  static const int fa_wpressr = 0xf3e4;

  static const int fa_wreath = 0xf7e2;

  static const int fa_wrench = 0xf0ad;

  static const int fa_x_ray = 0xf497;

  static const int fa_xbox = 0xf412;

  static const int fa_xing = 0xf168;

  static const int fa_xing_square = 0xf169;

  static const int fa_y_combinator = 0xf23b;

  static const int fa_yahoo = 0xf19e;

  static const int fa_yammer = 0xf840;

  static const int fa_yandex = 0xf413;

  static const int fa_yandex_international = 0xf414;

  static const int fa_yarn = 0xf7e3;

  static const int fa_yelp = 0xf1e9;

  static const int fa_yen_sign = 0xf157;

  static const int fa_yin_yang = 0xf6ad;

  static const int fa_yoast = 0xf2b1;

  static const int fa_youtube = 0xf167;

  static const int fa_youtube_square = 0xf431;

  static const int fa_zhihu = 0xf63f;
}
